<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WF.Cqrs.Crud\WF.Cqrs.Crud.csproj" />
        <ProjectReference Include="..\WF.Data\WF.Data.csproj" />
        <ProjectReference Include="..\WF.Domain\WF.Domain.csproj"/>
    </ItemGroup>

</Project>
